package com.github.abator.utils;

import java.util.Date;

public class Utils {

    private static final org.slf4j.Logger LOG = org.slf4j.LoggerFactory.getLogger(Utils.class);

    /**
     * Domain类名称
     * <p>
     * 首字母大写
     * </p>
     * @param name
     * @return Domain类名称
     */
    public static String getDomainName(String name) throws Exception {
        if (name.contains("-") && name.contains("_")) {
            name.replaceAll("-", "_");
        }
        String[] t = name.split("_");
        StringBuffer modelClassName = new StringBuffer();
        for (String s : t) {
            modelClassName.append(s.substring(0, 1).toUpperCase()).append(s.substring(1, s.length()));
        }
        LOG.debug(name + " to " + modelClassName.toString());
        return modelClassName.toString();
    }

    public static String getCamelName(String name) throws Exception {
        name = getDomainName(name);
        name = name.substring(0, 1).toLowerCase() + name.substring(1, name.length());
        return name;
    }

    public static void main(String[] args) throws Exception {
        System.out.println(Utils.getDomainName("aaaBaaa"));
        System.out.println(Utils.getDomainName("aa_a"));
    }

    public static String getSignature() {
        return "Generated by:http://github.com/xiebiao/Abator [ " + new Date() + " ]";
    }
}
